development:
  adapter: postgresql
  encoding: unicode
  database: homefinance
  pool: 5
  username: postgres
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: postgres
  password: 12345

production:
  adapter: postgresql
  encoding: unicode
  database: homefinance
  pool: 5
  username: postgres
  password: 12345
