module ApplicationHelper
  #transaction types
  TRANSACTION_TO_ACCOUNT = 0
  TRANSACTION_FROM_ACCOUNT_TO_ACCOUNT = 1
  TRANSACTION_FROM_ACCOUNT_TO_CASH = 2
  TRANSACTION_FROM_ACCOUNT_TO_CATEGORY = 3
  TRANSACTION_TO_CASH = 4
  TRANSACTION_FROM_CASH_TO_ACCOUNT = 5
  TRANSACTION_FROM_CASH_TO_CASH = 6
  TRANSACTION_FROM_CASH_TO_CATEGORY = 7

end
